### ISSUE TITLE
browser not working

### ISSUE THREAD

**Issue by ghost** [accetto/ubuntu-vnc-xfce-chromium#1]
can't open chromium browser
when I've downloaded firefox it shows that tab have been crashed 
please help 🙏🏻😔

**Comment by accetto** [comment]
Hello,

thanks for reporting an issue. However, I'm not able to reproduce it (see the screenshot).

Is it possible, that you need to increase the shared memory? This [Readme](https://github.com/accetto/xubuntu-vnc-novnc/tree/master/docker/xubuntu-vnc-novnc-firefox) describes that at least 256MB is needed for Firefox. Maybe it's similar also for Chrome. This [WIki page](https://github.com/accetto/xubuntu-vnc/wiki/Firefox-multiprocess#how-to-check-shared-memory-size-in-containers) describes how to check it.

You can also try some of my newer images. For example the [generation 2](https://github.com/accetto/xubuntu-vnc-novnc) or [generation 3](https://github.com/accetto/ubuntu-vnc-xfce-g3). You don't need to build them yourself, simply download the images from Docker Hub.

Let me know if you still have the issue after increasing the shared memory and/or trying the newer images.

Regards,
accetto

### Screenshot

![Screenshot__accetto__ubuntu-vnc-xfce-chromium](https://user-images.githubusercontent.com/34798830/146653815-77e769b1-1f30-442a-991b-1f742329e60f.JPG)

**Comment by accetto** [comment]
I was able to get a crash after decreasing the shared memory size to its (unfortunate!) default **64MB** and using the **noVNC Full Client** in the web browser.

After increasing the shared memory to **256MB** it's working fine. Just add the following line into the Docker daemon configuration file and restart the daemon:

`"default-shm-size": "256m"`
