### ISSUE TITLE
Using remote-debugging-port

### ISSUE THREAD

**Issue by IvanMMM** [accetto/ubuntu-vnc-xfce-chromium#2]
Hello
How can I use `--remote-debugging-port=9222` and expose it to the web?
Main idea is to have docker with exposed websocket connection to manipulate it with puppeteer
I tried to build my own Dockerfile on top of your image, but it didn't worked :(
Any ideas how to make it working?
```
FROM accetto/ubuntu-vnc-xfce-chromium-g3:latest

EXPOSE 6901
EXPOSE 5901
EXPOSE 9222
CMD ["/usr/bin/chromium-browser", "--remote-debugging-port=9222  --remote-debugging-address=127.0.0.1"]
```

**Comment by accetto** [comment]
Hello,

this image is internally pretty different than the image [accetto/ubuntu-vnc-xfce-chromium-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium-g3), becase it's much older, but conceptually it's the same. So I assume that the problems would have the same or similar reasons.

I never tested it with the **puppeteer**, so I unfortunatelly cannot provide any working solution at the moment.

Please try the things I've described by the [issue 21](https://github.com/accetto/ubuntu-vnc-xfce-g3/issues/21).

Regards,
accetto

**Comment by accetto** [comment]
By the way, there is also the image [accetto/xubuntu-vnc-novnc-chrome](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-chrome). Maybe you can try also it, for the case, that the **Chrome** would behave better than the **Chromium**.
